export const ACTION_TYPES = {
  SET_WATCHLATER: "SET_WATCHLATER",

  SET_INITIAL_PLAYLIST:"SET_INITIAL_PLAYLIST",
  SET_NEW_PLAYLIST:"SET_NEW_PLAYLIST",
  ADD_VIDEO_TO_EXISTING_PLAYLIST:"ADD_VIDEO_TO_EXISTING_PLAYLIST",
  DELETE_PLAYLIST:"DELETE_PLAYLIST",
  DELETE_VIDEO_FROM_PLAYLIST:"DELETE_VIDEO_FROM_PLAYLIST",

  ADD_NOTES:"ADD_NOTES",
  DELETE_NOTE:"DELETE_NOTE",
  EDIT_NOTE:"EDIT_NOTE"
};
